* tips
| functions                     | key       | link                            | remark |
|-------------------------------+-----------+---------------------------------+--------|
| org-capture                   | SPC-a-o-c |                                 |        |
| org-agenda                    | SPC-a-o-o |                                 |        |
| org-ctrl-c-ctrl-c             | ,,        |                                 |        |
| org-cycle                     | TAB       | [[*Visibility Cycling][Visibility Cycling]]              |        |
| org-global-cycle              | S-TAB     | [[*Visibility Cycling][Visibility Cycling]]              |        |
| org-insert-drawer             | ,id       | [[*Drawers][Drawers]]                         |        |
| org-insert-structure-template | ,ib       | [[*Blocks][Blocks]]                          |        |
| org-store-link                | SPC-a-o-l | [[*External Links][External Links]]                  |        |
| org-insert-link               | ,il       | [[*Internal Links][Internal Links]]                  |        |
| org-todo                      | ,TT       | [[*\TODO Basics][TODO Basics]]                     |        |
| org-show-todo-tree            | ,Tt       | [[*\TODO Basics][TODO Basics]]                     |        |
| org-todo-list                 | SPC-a-o-t | [[*\TODO Basics][TODO Basics]]                     |        |
| org-priority                  | ,p        | [[*Priorities][Priorities]]                      |        |
| org-tags-view                 | SPC-a-o-m | [[*Tag Searches][Tag Searches]] [[*Property Searches][Property Searches]]  |        |
| org-set-property              | ,ip       | [[*Property Syntax][Property Syntax]]                 |        |
  

* Document Structure
  
** Headlines

Use tab S-tab to cycling.

#+begin_src org
* Top level headline
** Second level
*** Third level
#+end_src

** Visibility Cycling

TAB(org-cycle)
S-TAB(org-global-cycle)


** Plain Lists

#+begin_src org
My favorite scenes are (in this order)
1. The attack of the Rohirrim
2. Eowyn's fight with the witch king
   + this was already my favorite scene in the book
   + I really like Miranda Otto.
3. Peter Jackson being shot by Legolas
   - on DVD only
   He makes a really funny face when it happens.
But in the end, no individual scenes matter but the film as a whole.
Important actors in this film are:
- Elijah Wood :: He plays Frodo
- Sean Astin :: He plays Sam, Frodo's friend.  I still remember him
     very well from his role as Mikey Walsh in /The Goonies/.
#+end_src

** Drawers
:DRAWERNAME:
Sometimes you want to keep information associated with an entry, but you normally do not want to see it.
:END:


Sometimes you want to keep information associated with an entry, but you normally do not want to see it.

,id(org-insert-drawer) 

** Blocks
   
Org mode uses ‘#+BEGIN’ … ‘#+END’ blocks for various purposes from including source code examples.

,ib(org-insert-structure-template) Block

* Tables

,tn(org-table-create)

TAB (org-table-next-field)

S-TAB (org-table-previous-field)

RET (org-table-next-row)

,ta(org-table-align)

** The Orgtbl Minor Mode
   
If you like the intuitive way the Org table editor works,
you might also want to use it in other modes like Text mode or Mail mode.
The minor mode Orgtbl mode makes this possible.
You can always toggle the mode with M-x orgtbl-mode.
To turn it on by default, 


** Org Plot

if use it, need gnuplot.


#+PLOT: title:"Citas" ind:1 deps:(3) type:2d with:histograms set:"yrange [0:]"
| Sede      | Max cites | H-index |
|-----------+-----------+---------|
| Chile     |    257.72 |   21.39 |
| Leeds     |    165.77 |   19.68 |
| Sao Paolo |     71.00 |   11.50 |
| Stockholm |    134.19 |   14.33 |
| Morelia   |    257.56 |   17.67 |

* Hyperlinks

** Link Format

#+begin_src shell
[[LINK][DESCRIPTION]]
[[LINK]]
#+end_src

** Internal Links

#+NAME: My Target
| a  | table      |
|----+------------|
| of | four cells |

[[My Target]]

,il(org-insert-link)

** External Links

SPC-a-o-l(org-store-link)   

** Search Options in File Links

#+begin_src shell
[[file:~/code/main.c::255]]
[[file:~/xx.org::My Target]]
[[file:~/xx.org::*My Target]]
[[file:~/xx.org::#my-custom-id]]
[[file:~/xx.org::/regexp/]]
[[attachment:main.c::255]]
#+end_src

- ‘255’
Jump to line 255.

- ‘My Target’
Search for a link target ‘<<My Target>>’,
or do a text search for ‘my target’,
similar to the search in internal links,
see Internal Links. In HTML export (see HTML Export),
such a file link becomes a HTML reference to the corresponding named anchor in the linked file.

- ‘*My Target’
In an Org file, restrict search to headlines.

‘#my-custom-id’
Link to a heading with a ‘CUSTOM_ID’ property

‘/REGEXP/’
Do a regular expression search for REGEXP.
This uses the Emacs command occur to list all matches in a separate window.
If the target file is in Org mode,
org-occur is used to create a sparse tree with the matches.

* \TODO Items

** \TODO Basics

,TT(org-todo)
,Tt(org-show-todo-tree)
SPC-a-o-t(org-todo-list)

#+begin_src shell
*** \TODO Write letter to Sam
#+end_src

** Extended Use of TODO Keywords


Org mode allows you to classify TODO items in more complex ways with TODO keywords (stored in org-todo-keywords).

For example:
#+begin_src elisp
(setq org-todo-keywords
      '((sequence "TODO(t)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELED(c@)")
        (sequence "REPORT(r!)" "BUG(b@/!)" "KNOWNCAUSE(k!)" "|" "FIXED(f@)")))
#+end_src

*** Setting up keywords for individual files

For file-local settings, you need to add special lines to the file which set the keywords and interpretation for that file only.
For example:
#+begin_src org
#+TODO: TODO | DONE
#+TODO: REPORT BUG KNOWNCAUSE | FIXED
#+TODO: | CANCELED
#+end_src

*** Faces for TODO keywords

. If you are using more than two different states,
you might want to use special faces for some of them.
This can be done using the variable org-todo-keyword-faces.
For example:
#+begin_src org
(setq org-todo-keyword-faces
      '(("TODO" . org-warning) ("STARTED" . "yellow")
        ("CANCELED" . (:foreground "blue" :weight bold))))    
#+end_src

*** \TODO dependencies

Sometimes there is a logical sequence to (sub)tasks,
so that one subtask cannot be acted upon before all siblings above it have been marked as done.
If you customize the variable org-enforce-todo-dependencies,
Org blocks entries from changing state to DONE while they have TODO children that are not DONE.
Furthermore, if an entry has a property ‘ORDERED’,
each of its TODO children is blocked until all earlier siblings are marked as done.

For example:

#+begin_src shell
* \TODO Blocked until (two) is done
** \DONE one
** \TODO two
#+end_src

#+begin_src shell
* Parent
:PROPERTIES:
:ORDERED:  t
:END:
** \TODO a
** \TODO b, needs to wait for (a)
** \TODO c, needs to wait for (a) and (b)
#+end_src

#+begin_src org
* This entry is never blocked
:PROPERTIES:
:NOBLOCKING: t
:END:
#+end_src

** Priorities

By default, Org mode supports three priorities: ‘A’, ‘B’, and ‘C’.
‘A’ is the highest priority.
An entry without a cookie is treated as equivalent if it had priority ‘B’.
Priorities make a difference only for sorting in the agenda (see Weekly/daily agenda).
Outside the agenda, they have no inherent meaning to Org mode. 
   
,p(org-priority)

#+begin_src shell
*** \TODO [#A] Write letter to Sam
#+end_src

** Breaking Down Tasks into Subtasks

It is often advisable to break down large tasks into smaller,
manageable subtasks. You can do this by creating an outline tree below a TODO item,
with detailed subtasks on the tree
To keep an overview of the fraction of subtasks that have already been marked as done,
insert either ‘[/]’ or ‘[%]’ anywhere in the headline

#+begin_src shell
* Organize Party [0%]
** \DONE Call people [1/2]
   CLOSED: [2021-01-28 Thu 11:14]
   - State "DONE"       from "TODO"       [2021-01-28 Thu 11:14]
*** \TODO Peter
    - State "DONE"       from "TODO"       [2021-01-28 Thu 11:13]
*** \DONE Sarah
** \DONE Buy food
   CLOSED: [2021-01-28 Thu 11:14]
   - State "DONE"       from "TODO"       [2021-01-28 Thu 11:14]
** \DONE Talk to neighbor
#+end_src

If a heading has both checkboxes and TODO children below it,
the meaning of the statistics cookie become ambiguous.
Set the property ‘COOKIE_DATA’ to either ‘checkbox’ or ‘todo’ to resolve this issue.
If you would like to have the statistics cookie count any TODO entries in the subtree (not just direct children),
configure the variable org-hierarchical-todo-statistics.
To do this for a single subtree,
include the word ‘recursive’ into the value of the ‘COOKIE_DATA’ property.
#+begin_src shell
* Parent capturing statistics [2/20]
  :PROPERTIES:
  :COOKIE_DATA: todo recursive
  :END:
#+end_src

** Checkboxes


#+begin_src shell
* \TODO Organize party [3/4]
  - [-] call people [2/3]
    - [X] Peter
    - [X] Sarah
    - [ ] Sam
  - [X] order food
  - [X] think about what music to play
  - [X] talk to the neighbors
#+end_src

* Tags

** Tag Inheritance

Tags make use of the hierarchical structure of outline trees.
If a heading has a certain tag, all subheadings inherit the tag as well.
For example, in the list

#+begin_src shell
* Meeting with the French group      :work:
** Summary by Frank                  :boss:notes:
*** \TODO Prepare slides for him                                     :action:
#+end_src
the final heading has the tags ‘work’, ‘boss’, ‘notes’,
and ‘action’ even though the final heading is not explicitly marked with those tags. 

** Setting Tags
    
,it(org-set-tags-command)

To set these mutually exclusive groups in the variable org-tags-alist,
you must use the dummy tags :startgroup and :endgroup instead of the braces.
Similarly, you can use :newline to indicate a line break.
The previous example would be set globally by the following configuration:
#+begin_src emacs-lisp
(setq org-tag-alist '((:startgroup . nil)
                      ("@work" . ?w) ("@home" . ?h)
                      ("@tennisclub" . ?t)
                      (:endgroup . nil)
                      ("laptop" . ?l) ("pc" . ?p)))

#+end_src

** Tag Hierarchy

Tags can be defined in hierarchies.
A tag can be defined as a group tag for a set of other tags.
The group tag can be seen as the “broader term” for its set of tags.
Defining multiple group tags and nesting them creates a tag hierarchy.
#+begin_src emacs-lisp 
(setq org-tag-alist '((:startgrouptag)
                      ("GTD")
                      (:grouptags)
                      ("Control")
                      ("Persp")
                      (:endgrouptag)
                      (:startgrouptag)
                      ("Control")
                      (:grouptags)
                      ("Context")
                      ("Task")
                      (:endgrouptag)))
#+end_src

** Tag Searches

SPC-a-o-m(org-tags-view)

* Properties and Columns

** Property Syntax

,ip(org-set-property)

#+begin_src shell
* CD collection
** Classic
*** Goldberg Variations
    :PROPERTIES:
    :Title:     Goldberg Variations
    :Composer:  J.S. Bach
    :Artist:    Glenn Gould
    :Publisher: Deutsche Grammophon
    :NDisks:    1
    :END:
#+end_src

You may define the allowed values for a particular property ‘Xyz’ by setting a property ‘Xyz_ALL’.
This special property is inherited,
so if you set it in a level 1 entry,
it applies to the entire tree.
When allowed values are defined,
setting the corresponding property becomes easier and is less prone to typing errors.
For the example with the CD collection, we can pre-define publishers and the number of disks in a box like this:

#+begin_src shell
* CD collection
  :PROPERTIES:
  :NDisks_ALL:  1 2 3 4
  :Publisher_ALL: "Deutsche Grammophon" Philips EMI
  :END:
#+end_src

** Special Properties

‘ALLTAGS’	All tags, including inherited ones.
‘BLOCKED’	t if task is currently blocked by children or siblings.
‘CATEGORY’	The category of an entry.
‘CLOCKSUM’	The sum of CLOCK intervals in the subtree. org-clock-sum
must be run first to compute the values in the current buffer.
‘CLOCKSUM_T’	The sum of CLOCK intervals in the subtree for today.
org-clock-sum-today must be run first to compute the
values in the current buffer.
‘CLOSED’	When was this entry closed?
‘DEADLINE’	The deadline timestamp.
‘FILE’	The filename the entry is located in.
‘ITEM’	The headline of the entry.
‘PRIORITY’	The priority of the entry, a string with a single letter.
‘SCHEDULED’	The scheduling timestamp.
‘TAGS’	The tags defined directly in the headline.
‘TIMESTAMP’	The first keyword-less timestamp in the entry.
‘TIMESTAMP_IA’	The first inactive timestamp in the entry.
‘TODO’	The TODO keyword of the entry.

** Property Searches

SPC-a-o-m(org-tags-view)

** Property Inheritance

The outline structure of Org documents lends itself to an inheritance model of properties:
if the parent in a tree has a certain property,
the children can inherit this property.
Org mode does not turn this on by default,
because it can slow down property searches significantly and is often not needed.
However, if you find inheritance useful,
you can turn it on by setting the variable org-use-property-inheritance.
It may be set to t to make all properties inherited from the parent,
to a list of properties that should be inherited,
or to a regular expression that matches inherited properties.
If a property has the value nil,
this is interpreted as an explicit un-define of the property,
so that inheritance search stops at this value and returns nil.

** Column View

wait completed.
